<?php

/** @var \Laravel\Lumen\Routing\Router $router */

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It is a breeze. Simply tell Lumen the URIs it should respond to
| and give it the Closure to call when that URI is requested.
|
*/
//todo 路由分组待优化
$router->get('/', function () use ($router) {
    return '$router->app->version()';
});
//搜索
$router->post('/search','CompanyController@search');
//公司列表
$router->get('/co_list','CompanyController@co_list');
//公司详情
$router->get('/co_detil','CompanyController@co_detil');
//添加公司
$router->post('/co_add','CompanyController@co_add');
//修改公司详情
$router->post('/co_edit','CompanyController@co_edit');
//组织架构搜索
$router->post('/de_search','DepartmentController@de_search');
//组织架构列表
$router->get('/de_list','DepartmentController@de_list');
//组织架构详情
$router->get('/de_detil','DepartmentController@de_detil');
//添加组织架构
$router->post('/de_add','DepartmentController@de_add');
//修改组织架构详情
$router->post('/de_edit','DepartmentController@de_edit');
//员工搜索
$router->post('/ee_search','EmployeeController@ee_search');
//员工列表
$router->get('/ee_list','EmployeeController@ee_list');
//员工详情
$router->get('/ee_detil','EmployeeController@ee_detil');
//添加员工
$router->post('/ee_add','EmployeeController@ee_add');
//修改员工详情
$router->post('/ee_edit','EmployeeController@ee_edit');
//公司关系图
$router->get('/co_tree','CompanyController@tree');
//单选框接口
$router->get('/co_select','CompanyController@co_select');
//合同搜索
$router->get('/con_search','ContractController@con_search');
//合同添加
$router->post('/con_add','ContractController@con_add');
//合同修改
$router->get('/con_edit','ContractController@con_edit');
//合同详情
$router->get('/con_detil','ContractController@con_detil');
//合同列表
$router->get('/con_list','ContractController@con_list');
//断点上传
$router->post('/resumable','ResumableController@process');
//员工删除
$router->get('/ee_delete','EmployeeController@ee_delete');
//公司删除
$router->get('/co_delete','CompanyController@co_delete');
//部门删除
$router->get('/de_delete','DepartmentController@de_delete');
//单个部门下的员工
$router->get('/de_per_list','DepartmentController@de_per_list');
//部门添加员工
$router->get('/de_add_ee','DepartmentController@de_add_ee');
//公司所有部门
$router->get('/de_per_co','CompanyController@de_per_co');
//添加公告
$router->post('/add_bbs','BbsController@add_bbs');
//查看公告
$router->get('/see_bbs','BbsController@see_bbs');
//公告列表
$router->get('/bbs_list','BbsController@bbs_list');
//公告删除
$router->get('/bbs_delete','BbsController@bbs_delete');
//组织关系图
$router->get('/de_tree','DepartmentController@de_tree');
//添加项目
$router->get('/proj_add','ProjectController@proj_add');
//项目列表
$router->get('/proj_list','ProjectController@proj_list');
//合同删除
$router->get('/con_delete','ContractController@con_delete');
//项目详情
$router->get('/proj_detil','ProjectController@proj_detil');
//项目编辑
$router->post('/proj_edit','ProjectController@proj_edit');
//角色列表
$router->get('/role_list','EmployeeController@role_list');
//权限列表
$router->get('/permission_list','EmployeeController@permission_list');
//图片上传
$router->post('/upload_img','FileController@upload_img');
//供应商图片删除
$router->get('/delete_img','FileController@delete_img');
//领导列表
$router->get('/lead_list','ContractController@lead_list');
//项目删除
$router->get('/proj_delete','ProjectController@proj_delete');
//添加角色
$router->get('/role_add','RoleController@role_add');
//角色所有的权限
$router->get('/role_permission','RoleController@role_permission');
//角色详情
$router->get('/role_info_detail','RoleController@role_info_detail');
//角色编辑
$router->get('/role_info_edit','RoleController@role_info_edit');
//删除角色
$router->get('/role_delete','RoleController@role_delete');
//系统所有的权限
$router->get('/all_permission','RoleController@all_permission');
//角色权限修改
$router->get('/role_change_permission','RoleController@role_change_permission');
//添加权限
$router->get('/permission_add','RoleController@permission_add');
//合同所属公司
$router->get('/con_company','ContractController@con_company');
//供应商图片上传
$router->post('/supplier_img','FileController@supplier_img');
//商品图片上传
$router->post('/goods_img','FileController@goods_img');
//员工档案图片上传
$router->post('/arch_img_add','FileController@arch_img_add');
//商品图片删除
$router->get('/goods_img_delete','FileController@goods_img_delete');
//项目图片删除
$router->get('/proj_img_delete','FileController@proj_img_delete');
//excel导出测试
$router->get('/excel','FileController@excel');
//供应商添加
$router->post('/supplier_add','SupplierController@supplier_add');
//供应商图片修改
$router->get('/supplier_img_edit','SupplierController@supplier_img_edit');
//客户添加
$router->get('/customer_add','CustomerController@customer_add');
//客户删除
$router->get('/customer_delete','CustomerController@customer_delete');
//客户修改
$router->get('/customer_edit','CustomerController@customer_edit');
//添加账号
$router->get('/account_add','AccountController@account_add');
//账号库删除
$router->get('/account_delete','AccountController@account_delete');
//账号库修改
$router->get('/account_edit','AccountController@account_edit');
//供应商列表 增加登录认证
$router->get('/supplier_list','SupplierController@supplier_list');

//需要认证的路由分组
$router->group(['middleware' => 'auth'],function () use ($router){
    //修改密码
    $router->post('/change_password','UserController@change_password');
    //用户信息
    $router->get('/user_info','UserController@user_info');
    //合同审核
    $router->get('/con_access','ContractController@con_access');
    //商品添加
    $router->get('/goods_add','GoodsController@goods_add');

});
//供应商详情
$router->get('/supplier_detil','SupplierController@supplier_detil');
//供应商导出excel
$router->get('/supplier_excel','SupplierController@supplier_excel');
//供应商删除
$router->get('/supplier_delete','SupplierController@supplier_delete');
//供应商证书日期检查
//$router->get('/date_check','SupplierController@date_check');
//供应商单选
$router->get('/supplier_select','SupplierController@supplier_select');
//客户列表
$router->get('/customer_list','CustomerController@customer_list');
//账号列表
$router->get('/account_list','AccountController@account_list');
//客户详情
$router->get('/customer_detil','CustomerController@customer_detil');
//商品列表
$router->get('/goods_list','GoodsController@goods_list');
//商品删除
$router->get('/goods_delete','GoodsController@goods_delete');
//商品更改
$router->get('/goods_edit','GoodsController@goods_edit');
//商品详情
$router->get('/goods_detail','GoodsController@goods_detail');
//商品选择分类
$router->get('/cat_select','GoodsController@cat_select');
//商品搜索
$router->get('/goods_search','GoodsController@goods_search');
//菜单
$router->get('/menu','MenuController@menu');
//登录
$router->get('/login','UserController@login');
//员工档案添加
$router->get('/arch_add','ArchivesController@arch_add');
//员工姓名库
$router->get('/all_name','ArchivesController@all_name');
//员工档案删除
$router->get('/arch_delete','ArchivesController@arch_delete');
//员工档案详情
$router->get('/arch_detail','ArchivesController@arch_detail');
//员工档案列表
$router->get('/arch_list','ArchivesController@arch_list');
//员工档案修改
$router->get('/arch_edit','ArchivesController@arch_edit');
//消息通知
$router->get('/read','UserController@read');
//消息列表
$router->get('/massage_list','UserController@massage_list');
//员工档案图片删除
$router->get('/arch_img_delete','FileController@arch_img_delete');



